### ISSUE TITLE
Add Purgecss to remove bloat of compiled css

### ISSUE THREAD

**Issue by fieu** [utkarshkukreti/tailwind.run#12]
I think maybe adding [Purgecss](https://www.purgecss.com/) as option of seperate tab next to "Compiled CSS" would be pretty cool for people that would like to take the CSS that's needed to render their HTML.

**Comment by utkarshkukreti** [comment]
I've added a new tab under "CSS" which shows the Purged CSS for inspection. I've also added it to the Exported zip along with a commented out `<link rel="stylesheet" ...` pointing to it. You can now export the zip and modify one line in `index.html` to start using the purged css.

Let me know if it works for you!

**Comment by fieu** [comment]
Nice, appreciate it. Love the project :smile: :+1:

**Comment by daltonlp** [comment]
Is this working?   The contents of the "purge" tab are always blank.

I've tried explicitly enabling purge in the config, as well as the default /new config.

**Comment by fieu** [comment]
@daltonlp I don't think it's implemented.

**Comment by MikeM88** [comment]
Would love to see the Purge functionality up and running!

**Comment by fieu** [comment]
2 years have gone by, all good @utkarshkukreti ? Haha 😄

**Comment by fieu** [comment]
Obviously this project is dead. The repository is even empty. Closing.
