### ISSUE TITLE
Tailwind UI support

### ISSUE THREAD

**Issue by vortechron** [utkarshkukreti/tailwind.run#23]
I try to import tailwindcss/ui plugin, get this error:
`Error: Error: Cannot find module '@tailwindcss/ui' `

what i did:
```
module.exports = {
  plugins: [require('ts')],
};
```

**Comment by innocenzi** [comment]
You can't import plugins with `tailwind.run` (except for the custom forms one). And it is not up to date anyway, it's on an older version of Tailwind right now.

**Comment by utkarshkukreti** [comment]
I've added support for Tailwind 1.2 and it now includes `@tailwindcss/ui`. It's commented out by default right now. Just open tailwind.run, go to the Config tab, and enable it. Please let me know if it works for you!

**Comment by andreich1980** [comment]
@utkarshkukreti thanks for the update!

By the way, you've also commented `require('@tailwindcss/custom-forms'),` but you still use the classes on your demo example. So please uncomment this line.

```javascript
  plugins: [
    require('@tailwindcss/custom-forms'), // Uncomment this line please
    // require('@tailwindcss/ui'),
  ],
```

**Comment by vortechron** [comment]
tq @utkarshkukreti
