### ISSUE TITLE
Redirect main link to latest saved version

### ISSUE THREAD

**Issue by stephenturvey** [utkarshkukreti/tailwind.run#6]
Currently it creates a new URL with each save, ie:

tailwind.run/aBcDeF/1
tailwind.run/aBcDeF/2

This makes it difficult to share the link and collaborate because the URL is always changing. Perhaps make the root link auto redirect to the latest saved version?

So tailwind.run/aBcDeF/ would go straight to tailwind.run/aBcDeF/24 or whatever.

**Comment by utkarshkukreti** [comment]
`/aBcDeF/` already shows the first version so I've made `/aBcDeF/latest` redirect to the latest revision. Does that work for you?

**Comment by stephenturvey** [comment]
Yes! Thanks.

**Comment by utkarshkukreti** [comment]
👍
